export const teams = {
  Angels: '/angels.svg',
  Astros: '/astros.svg',
  Athletics: '/athletics.svg',
  'Blue Jays': '/blue-jays.svg',
  Braves: '/braves.svg',
  Brewers: '/brewers.svg',
  Cardinals: '/cardinals.svg',
  Cubs: '/cubs.svg',
  Dbacks: '/dbacks.svg',
  Diamondbacks: '/dbacks.svg',
  Dodgers: '/dodgers.svg',
  Giants: '/giants.svg',
  Indians: '/indians.svg',
  Mariners: '/mariners.svg',
  Marlins: '/marlins.svg',
  Mets: '/mets.svg',
  Nationals: '/nationals.svg',
  Orioles: '/orioles.svg',
  Padres: '/padres.svg',
  Phillies: '/phillies.svg',
  Pirates: '/pirates.svg',
  Rangers: '/rangers.svg',
  Rays: '/rays.svg',
  'Red Sox': '/red-sox.svg',
  Reds: '/reds.svg',
  Rockies: '/rockies.svg',
  Royals: '/royals.svg',
  Tigers: '/tigers.svg',
  Twins: '/twins.svg',
  'White Sox': '/white-sox.svg',
  Yankees: '/yankees.svg',
};
